blueprint:
  name: Trigger Fan On High Humidity
  description: Turns a Fan on in high humidity situations, envisioned as a bathroom fan switch.
  domain: automation
  input:
    humidity_sensor:
      name: Humidity Sesnor
      description: The Sensor to trigger the fan.
      selector:
        entity:
          domain: sensor
    reference_humidity:
        name: Reference Humidity
        description: A percentage point value that indicates the baseline humidity if there is no reference sensor available
        default: 60
    reference_humidity_sensor:
        name: Reference Humidity Sensor
        description: A sensor that indicates the baseline humidity of the location
        selector:
          entity:
            domain: sensor
        default: []
    fan_switch:
      name: Fan to Turn on
      description: The fan desired to turn on.
      selector:
        entity:
          domain: switch
    rising_threshold:
      name: On Threshold Value
      description: How many percentage points above the reference humidity the sensor can rise before the fan is turned on
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
      default: 8

    falling_threshold:
      name: Off Threshold Value
      description: How many percentage points above the reference humidity the sensor must fall to before the fan is turned off
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
      default: 3

variables:
  humidity_sensor: !input humidity_sensor
  reference_humidity: !input "reference_humidity"
  reference_humidity_sensor: !input reference_humidity_sensor
  fan_switch: !input fan_switch
  switch_state: '{{ states(fan_switch) }}'
  rising_threshold: !input rising_threshold
  falling_threshold: !input falling_threshold
  difference: '{{ states(humidity_sensor)|float - (states(reference_humidity_sensor)|float or reference_humidity|float) }}'
  mode: '{% if switch_state == ''off'' and difference|float > rising_threshold|float %}on{% elif switch_state == ''on'' and difference|float > falling_threshold|float %}on{% else %}off{% endif %}'
trigger:
  - entity_id: !input humidity_sensor
    platform: state
  - entity_id: !input reference_humidity_sensor
    platform: state
condition:
  - condition: template
    value_template: '{{ mode != switch_state }}'
condition: []
action:
  - service: switch.turn_{{mode}}
    entity_id: !input fan_switch
mode: single
